# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    easyarm_servo_controller:
      type: easyarm_controller/EasyArmServoController

    easyarm_drag_controller:
      type: easyarm_controller/EasyArmDragController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
      - Joint6
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    constraints:
      stopped_velocity_tolerance: 0.1

easyarm_servo_controller:
  ros__parameters:
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
      - Joint6
    command_interfaces:
      - position
      - velocity
      - kp
      - kd
      - effort
    state_interfaces:
      - position
    command_timeout_sec: 0.2
    enable_gravity_compensation: true
    gravity_compensation_scale: 1.0
    kp: 120.0
    kd: 3.0

easyarm_drag_controller:
  ros__parameters:
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
      - Joint6
    command_interfaces:
      - position
      - velocity
      - kp
      - kd
      - effort
    state_interfaces:
      - position
    enable_gravity_compensation: true
    gravity_compensation_scale: 1.0
    kd: 0.10
